version: '3.8'

services:

  db_bizina:
    image: postgres
    container_name: db_bizina
    restart: always
    ports:
      - "5002:5432"
    environment:
      POSTGRES_DB: bizina
      POSTGRES_USER: bizina
      POSTGRES_PASSWORD: 123456
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pga_bizina:
    image: dpage/pgadmin4
    container_name: pga_bizina
    restart: always
    ports:
      - "5001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dina@bizina.com
      PGADMIN_DEFAULT_PASSWORD: P@ssW0rd#AMWebSolution
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: